server:
  port: 9002
spring:
  application:
    name: yd-service-gateway
  ## 网关配置
  cloud:
    gateway:
      routes:
        - id: service-autodeliver-router
          uri: lb://yd-service-autodeliver
          predicates:
            - Path=/autodeliver/**
        - id: service-resume-router
          uri: lb://yd-service-resume
          predicates:
            - Path=/resume/**
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
eureka:
  client:
    service-url:
      defaultZone: http://EurekaServerA:8761/eureka/,http://EurekaServerB:8762/eureka/
    ## 每隔30秒拉取一次服务列表
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    ## 租约续约时间间隔 默认 30秒
    lease-renewal-interval-in-seconds: 30
    ## 租约到期, 服务失效时间，默认90秒，服务超过90秒没有发生心跳，将从注册中心移除
    lease-expiration-duration-in-seconds: 90
